services:
  - type: web
    name:  BE_WASH
    env: node
    plan: free
    branch: master
    buildCommand: npm run build
    startCommand: node dist/server.js
    envVars:
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.pzvtpphhmcnxbkdfjith
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: JWT_EXPIRES_IN
        value: 30d
